Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.56.40"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL

    # Update packages
    sudo apt update -y

    # Install Nginx
    sudo apt install nginx -y

    # Create simple HTML page
    echo "<h1>Hello from Nginx Provisioned by Vagrant 🚀</h1>" | sudo tee /var/www/html/index.html

    # Restart Nginx
    sudo systemctl restart nginx

  SHELL
end
